#!/bin/sh
#
# Configuring system monitor.
#
case "$1" in
start)
    printf "Starting system monitor"
    /bin/monitor&
    printf "Started server HTTP"
    /bin/server
    printf "ok"
;;
stop)
    exit 1
;;
restart|reload)
    "$0" stop
    "$0" start
;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
